codecov:
  branch: main
  strict_yaml_branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
